// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq98D2dtfmd2pZrql15eDbgzBKwOaPERY',
    appId: '1:508114516420:web:007f4e67cca54f1ddc4c91',
    messagingSenderId: '508114516420',
    projectId: 'beneboba-1cc04',
    authDomain: 'beneboba-1cc04.firebaseapp.com',
    storageBucket: 'beneboba-1cc04.appspot.com',
    measurementId: 'G-9SK2BJKMVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOPREuDqPdoYheoCNDsG_1Hw8iAQLcwQ0',
    appId: '1:508114516420:android:25ed810074e39297dc4c91',
    messagingSenderId: '508114516420',
    projectId: 'beneboba-1cc04',
    storageBucket: 'beneboba-1cc04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW5IQxL8k5wk98TXbdqRKfR64DgxtGDB4',
    appId: '1:508114516420:ios:3f13611994156db7dc4c91',
    messagingSenderId: '508114516420',
    projectId: 'beneboba-1cc04',
    storageBucket: 'beneboba-1cc04.appspot.com',
    iosClientId: '508114516420-gralgoee3o6j1up0g2bf2djcv6qplmav.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSmarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW5IQxL8k5wk98TXbdqRKfR64DgxtGDB4',
    appId: '1:508114516420:ios:3f13611994156db7dc4c91',
    messagingSenderId: '508114516420',
    projectId: 'beneboba-1cc04',
    storageBucket: 'beneboba-1cc04.appspot.com',
    iosClientId: '508114516420-gralgoee3o6j1up0g2bf2djcv6qplmav.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSmarthome',
  );
}
